
dataset: lrsw

#### datasets
datasets:
  train:
    dist: False
    root: ./dataset/lrsw
    use_shuffle: true
    n_workers: 2  
    batch_size: 32
    use_flip: true
    use_crop: true
    patch_size: 96

  val:
    dist: False
    root: ./dataset/lrsw
    n_workers: 1
    use_crop: true
    batch_size: 1 



